// ============================================================
// Challenge-Pool nach Location-Modus + Schwierigkeitsgrad.
// Massiv erweiterter Pool — 20+ Challenges pro Bucket.
// ============================================================

export const LOCATION_MODES = [
  { id: 'bar', label: 'Bar-Modus', icon: '🍸', desc: 'Bestellungen, Barkeeper, fremde Leute' },
  { id: 'festival', label: 'Festival-Modus', icon: '🎪', desc: 'Crowd, Musik, Tanzen, Chaos' },
  { id: 'hostel', label: 'Hostel-Modus', icon: '🎒', desc: 'Reisende, neue Leute, Gemeinschaftsraum' },
  { id: 'houseparty', label: 'Hausparty-Modus', icon: '🏠', desc: 'Klassiker, Gruppenspiele, vertraute Runde' },
  { id: 'vacation', label: 'Urlaub-Modus', icon: '🏖️', desc: 'Strand, Pool, Sightseeing, Souvenirs' },
]

export function getLocationMode(id) {
  return LOCATION_MODES.find((m) => m.id === id) || LOCATION_MODES[3]
}

export const CHALLENGES_BY_LOCATION = {

  // ════════════════════════════════════════════════════════
  // 🍸 BAR
  // ════════════════════════════════════════════════════════
  bar: {
    easy: [
      'Bestell einen Drink mit einem Fantasienamen.',
      'Frag den Barkeeper nach seinem besten Trick.',
      'Finde jemanden, der das gleiche trinkt wie du.',
      'Stoß mit drei verschiedenen Personen an.',
      'Tausch deinen Barhocker für eine Runde.',
      'Mach ein Foto mit dem Barkeeper.',
      'Finde jemanden an der Bar mit einer Sonnenbrille.',
      'Sag dem Barkeeper, dass er heute besonders gut aussieht.',
      'Bestell deinen nächsten Drink auf Englisch.',
      'Finde jemanden an der Bar, der Geburtstag hat oder hatte.',
      'Mach 20 Sekunden lang den "Matrix"-Slow-Motion-Move.',
      'Zeig dem Spieler links deinen Kontostand — oder erfinde einen.',
      'Finde jemanden mit Kreditkarte und frag ihn, was sein Lieblingsdrink ist.',
      'Tausch für 2 Minuten den Platz mit dem Spieler rechts von dir.',
      'Ruf "Cheers!" und schau, wer mitanstößt.',
      'Benutze das nächste Mal wenn du was sagst drei mal das Wort "episch".',
      'Lass den Barkeeper dein Getränk raten.',
      'Bestell etwas für eine fremde Person an der Bar — was du magst.',
      'Finde jemanden der eine Uhr trägt und frag ihn wie spät es ist.',
      'Zeig dein Handy-Hintergrundbild dem Barkeeper.',
    ],
    medium: [
      'Bestell auf eine Art, die dich zum Lachen bringt.',
      'Frag eine fremde Person an der Bar nach einer Drink-Empfehlung.',
      'Bring den Barkeeper zum Lächeln – ohne ein Wort zu sagen.',
      'Finde jemanden mit einem Cocktail und beschreib, wie er wohl schmeckt.',
      'Lass dir von jemand Fremdem dein Lieblingsgetränk vorschlagen.',
      'Stell dich einer fremden Gruppe vor und sag, du bist der/die berühmteste Person aus deiner Stadt.',
      'Frag drei verschiedene Leute an der Bar nach ihrer Lieblingsbar.',
      'Beschreib deinen Drink so, als wärst du ein Sommelier.',
      'Finde jemanden, der allein sitzt, und sag ihm ein echtes Kompliment.',
      'Mach mit einer fremden Person an der Bar einen Handshake aus.',
      'Sag dem Barkeeper einen Witz und schau ob er lacht.',
      'Finde jemanden mit einem Cocktailschirm in seinem Drink.',
      'Imitiere den Barkeeper für 30 Sekunden.',
      'Frag drei Fremde nach ihrem Lieblings-Film.',
      'Erkläre einem Fremden, was dein Drink über deine Persönlichkeit sagt.',
      'Stell dich einer Gruppe Fremder mit einem falschen Beruf vor.',
      'Lass die Gruppe entscheiden, was du als Nächstes bestellst.',
      'Frag den Barkeeper nach dem ältesten Gast, den er je hatte.',
      'Such dir jemanden aus und überzeuge ihn, deinen Drink zu probieren.',
      'Erkläre dem Spieler rechts, wie er seinen Drink korrekt trinken soll.',
    ],
    hard: [
      'Bring einen Fremden dazu, mit dir auf Video "Cheers" zu sagen.',
      'Frag den Barkeeper nach der peinlichsten Bestellung des Abends.',
      'Lass dir von einer fremden Person ein Kompliment auf Video geben.',
      'Tausch für eine Runde deinen Platz mit jemand Fremdem an der Bar.',
      'Erzähl der Bar-Crowd einen Witz und filme die Reaktion.',
      'Finde jemanden Fremdes und überzeuge ihn, in die Gruppe aufgenommen zu werden.',
      'Bestell auf eine Sprache die du nicht sprichst — frag vorher einen Fremden wie.',
      'Mach eine 30-Sekunden Standup-Performance an der Bar.',
      'Bring 5 Fremde dazu, gleichzeitig anzustoßen.',
      'Frag eine fremde Person: "Was ist dein größtes Geheimnis?" und film die Reaktion.',
      'Überzeuge den Barkeeper, dir einen Gratis-Drink zu machen — mit Charme, nicht mit Geld.',
      'Finde jemanden mit einem teuren Getränk und frag ihn, ob du einen Schluck haben kannst.',
      'Stell dich 5 Fremden einzeln vor, jedes Mal mit einem anderen erfundenen Namen.',
      'Tausch für 5 Minuten dein Handy mit dem Spieler links — du darfst nichts anschauen.',
      'Bring eine fremde Person dazu, ihr peinlichstes Bar-Erlebnis zu erzählen.',
      'Setz dich für 2 Minuten allein an die Bar und streich alle anderen.',
      'Lass einen Fremden entscheiden, was du als Nächstes trinkst.',
      'Mach ein Selfie mit drei verschiedenen Fremden.',
      'Frag 5 Fremde: "Wer bist du wirklich?" und film die Antworten.',
      'Übernimm für 1 Minute den Barhocker eines Fremden — mit seiner Erlaubnis.',
    ],
    chaos: [
      'Lass den Barkeeper deinen nächsten Drink aussuchen – Augen zu.',
      'Eine fremde Person an der Bar entscheidet, wer als Nächstes bestraft wird.',
      'Tausch für 2 Runden deinen Namen mit der Person neben dir an der Bar.',
      'Lass die Gruppe entscheiden: dein nächster Drink wird mit etwas gemischt.',
      'Frag drei Fremde nacheinander nach ihrem peinlichsten Bar-Moment.',
      'Steh für 3 Minuten auf deinem Stuhl — wer kommentiert, trinkt.',
      'Übernimm für 1 Minute die Rolle des Barkeepers und nimm Bestellungen auf.',
      'Alle Mitspieler geben dir eine Aufgabe — du führst die schwerste aus.',
      'Bestell laut einen Drink, den es nicht gibt und überzeuge den Barkeeper, ihn zu erfinden.',
      'Wer als Letzter einen Fremden zum Lachen bringt, trinkt doppelt.',
      'Vertausch heimlich die Getränke zweier Mitspieler — ohne dass sie es merken.',
      'Bring die gesamte Gruppe dazu, gleichzeitig "Prost!" zu rufen.',
      'Ruf laut "Wer ist hier Single?" — die erste Person die sich meldet, bekommt von dir ein Kompliment.',
      'Lass einen zufälligen Fremden dein nächstes Dare bestimmen.',
      'Alle stehen auf — wer sich als Letzter setzt, zahlt die nächste Runde.',
      'Tausch für 3 Runden dein Getränk mit dem des Spielers gegenüber.',
      'Überzeuge eine Fremde Gruppe dazu, einen einstudier­ten Gruppen-Toast mit euch zu machen.',
      'Die Gruppe wählt: entweder du trinkst doppelt, oder du rufst laut deinen vollständigen Namen.',
      'Lass drei Fremde abstimmen wer von euch der coolste in der Gruppe ist.',
      'Wer zuerst sein Glas abstellt, trinkt noch einen.',
    ],
  },

  // ════════════════════════════════════════════════════════
  // 🎪 FESTIVAL
  // ════════════════════════════════════════════════════════
  festival: {
    easy: [
      'Finde jemanden mit Glitzer im Gesicht.',
      'Tanze 15 Sekunden lang zur Musik um dich herum.',
      'Finde ein Outfit in deiner Lieblingsfarbe in der Crowd.',
      'Mach mit drei Fremden eine Gruppen-Pose.',
      'Bring jemanden dazu, mit dir mitzusingen.',
      'Finde jemanden der einen Hut trägt.',
      'Winke einem Fremden zu — warte auf die Reaktion.',
      'Finde jemanden mit Festival-Wristband.',
      'Mach ein Foto mit dem ersten Fremden der dir begegnet.',
      'Sag einer fremden Person, dass du ihren Style liebst.',
      'Tanz für 10 Sekunden mit geschlossenen Augen.',
      'Finde jemanden, der denselben Lieblingskünstler hat wie du.',
      'Bring eine fremde Person dazu dir beizubringen wie man "Cool" in ihrer Sprache sagt.',
      'Finde jemanden der ein Tier-Kostüm oder -Accessoire trägt.',
      'Mach die beste Air-Guitar-Performance für 15 Sekunden.',
      'Sing die erste Zeile eines aktuellen Chart-Hits laut vor.',
      'Finde jemanden mit einer gemalten Flagge auf der Wange.',
      'Steh für 30 Sekunden so still wie möglich mitten in der Crowd.',
      'Finde jemanden der ein Festival-Merchandise-Shirt trägt.',
      'Zeig deinen besten "unbeeindruckten Festivalbesucher"-Gesichtsausdruck.',
    ],
    medium: [
      'Lerne den Tanzmove der Person neben dir und mach ihn nach.',
      'Finde jemanden mit Face-Paint und frag, wer es gemalt hat.',
      'Starte eine Welle mit mindestens 5 Leuten um dich herum.',
      'Tausch für eine Stunde Armbänder mit jemand Fremdem.',
      'Bring eine fremde Gruppe dazu, mit dir zu jubeln.',
      'Finde jemanden der gerade neu auf dem Festival angekommen ist und erklär ihm die "wichtigsten Regeln".',
      'Mach ein Boomerang-Video mit 5 Fremden.',
      'Finde jemanden der den gleichen Künstler liebt wie du.',
      'Bring eine fremde Person dazu, mit dir zu tanzen — 20 Sekunden mindestens.',
      'Erkläre einer fremden Person die besten 3 Hacks fürs Festival.',
      'Finde jemanden der vor dem Festival schon sehr müde aussieht.',
      'Bring eine Gruppe Fremder dazu, zusammen ein Foto zu machen.',
      'Improvisiere einen Rap über das Festival — 15 Sekunden, vor Fremden.',
      'Finde jemanden der komplett anders aussieht als du und mach ein Duo-Selfie.',
      'Bring 5 Fremde dazu, gleichzeitig ihre Hände zu heben.',
      'Mach die beste "Ich bin ein alter Festival-Veteran"-Imitation.',
      'Tausch deine Sonnenbrille für 10 Minuten mit einem Fremden.',
      'Finde jemanden der ein Selfie-Stick benutzt und bitte um ein Foto.',
      'Erkläre dem Spieler links was dein Outfit über dich sagt.',
      'Bring eine Gruppe Fremder dazu mit dir einen Countdown zu machen.',
    ],
    hard: [
      'Bring eine komplett fremde Gruppe dazu, ein Foto mit dir zu machen.',
      'Lerne in 2 Minuten den Namen von 3 Fremden und stell sie der Gruppe vor.',
      'Starte einen Tanz-Circle und bring 5 Leute zum Mitmachen.',
      'Frag jemand Fremdes nach seinem besten Festival-Erlebnis – auf Video.',
      'Bring die Crowd um dich herum dazu, deinen Namen zu rufen.',
      'Führe ein Mini-Interview mit 3 Fremden durch: "Warum bist du hier?"',
      'Bring jemanden dazu, dir spontan einen Spitznamen zu geben.',
      'Organisiere einen spontanen Chor mit 5 Fremden für 10 Sekunden.',
      'Überzeuge eine fremde Gruppe, euch für 5 Minuten zu joinen.',
      'Finde jemanden mit dem coolsten Outfit und überzeuge ihn zu einem kurzen Catwalk.',
      'Bring eine Reihe Fremder dazu, auf ein Zeichen von dir gleichzeitig zu jubeln.',
      'Starte einen Trend: Erfinde eine Bewegung und bring 5 Fremde dazu, sie nachzumachen.',
      'Filminteriew: Frag 5 Fremde "Was ist dein Festival-Lebensmotto?"',
      'Bring die Person neben dir dazu, dich für 30 Sekunden auf den Schultern zu tragen.',
      'Überzeuge einen Fremden, dir seinen Lieblingssong vorzusingen.',
      'Finde den lautesten Schreier in der Nähe und übertriff ihn.',
      'Bring 10 Fremde dazu, gleichzeitig zu klatschen.',
      'Überzeuge eine Gruppe, dir einen Stimmungs-Lift zu geben: alle rufen "Du schaffst das!"',
      'Sag auf Video einem Fremden, warum er der coolste Festivalgänger ist.',
      'Bring jemanden dazu, dir seine Festival-Flagge oder sein Accessoire zu leihen.',
    ],
    chaos: [
      'Eine fremde Person aus der Crowd entscheidet, wer bestraft wird.',
      'Tausch für 2 Runden ein Kleidungsstück mit jemand Fremdem.',
      'Lass dir von der Gruppe um dich herum eine Mini-Choreo beibringen.',
      'Der lauteste Fremde in deiner Nähe wählt deine nächste Challenge.',
      'Sammle High-Fives von 10 Fremden in 60 Sekunden.',
      'Alle Mitspieler stimmen ab — du machst den Move den die Mehrheit wählt.',
      'Tausch für 10 Minuten deinen Platz mit dem Spieler gegenüber von dir.',
      'Finde jemanden und überzeuge ihn, der Gruppe seinen besten Schrei zu geben.',
      'Die Gruppe wählt einen Fremden — du musst ihn in 60 Sekunden als Freund gewinnen.',
      'Lass die Crowd abstimmen: bist du ein "Main-Stage-Typ" oder ein "Hidden-Gem-Fan"?',
      'Bring alle Mitspieler dazu, 30 Sekunden lang zu tanzen — wer aufhört, trinkt.',
      'Die nächste fremde Person die an euch vorbeiläuft, entscheidet wer die Runde verliert.',
      'Alle legen ihr Handy in die Mitte — wer es als Erster nimmt, trinkt doppelt.',
      'Lass 3 Fremde per Abstimmung entscheiden, wer in der Gruppe am lustigsten ist.',
      'Tausch für eine Runde alle deine Taschen-Inhalte mit dem Spieler links.',
      'Bring die gesamte Gruppe dazu, 10 Sekunden lang gleichzeitig zu schweigen.',
      'Wer als Letztes aufhört zu tanzen wenn die Musik stoppt, bestimmt das nächste Dare.',
      'Alle Mitspieler wählen ein Wort — du baust daraus einen Satz und sagst ihn laut zu Fremden.',
      'Lass einen Fremden entscheiden, welcher Mitspieler die nächste Strafe bekommt.',
      'Übernimm für 2 Runden den Charakter-Namen des Spielers rechts von dir.',
    ],
  },

  // ════════════════════════════════════════════════════════
  // 🎒 HOSTEL
  // ════════════════════════════════════════════════════════
  hostel: {
    easy: [
      'Frag jemanden im Gemeinschaftsraum, woher er kommt.',
      'Finde jemanden, der aus einem anderen Land kommt als du.',
      'Tausch ein Reise-Tipp mit einem Fremden im Hostel.',
      'Finde jemanden mit dem gleichen Rucksack-Typ wie du.',
      'Stell dich drei Leuten im Gemeinschaftsraum vor.',
      'Frage einen Fremden nach seinem Lieblingsreiseziel.',
      'Find someone who has visited more than 10 countries.',
      'Finde jemanden der auf dem Weg nach Hause ist.',
      'Frag jemanden: "Was ist das Verrückteste, das dir auf Reisen passiert ist?"',
      'Finde jemanden, der ein Buch liest oder ein E-Book dabei hat.',
      'Zeig einem Fremden dein Lieblingsfoto aus dieser Reise.',
      'Frag jemanden, was sein nächstes Reiseziel ist.',
      'Finde jemanden der mehr als 3 Sprachen spricht.',
      'Lerne "Hallo" in der Sprache der Person neben dir.',
      'Frag drei Fremde nach einer Restaurantempfehlung vor Ort.',
      'Finde jemanden der gerade erst angekommen ist.',
      'Zeig einem Fremden deinen Reiseplan und frag nach Tipps.',
      'Finde jemanden der ein Souvenir dabei hat und lass es dir zeigen.',
      'Frag jemanden: "Was fehlt dir gerade am meisten von Zuhause?"',
      'Finde jemanden der allein reist.',
    ],
    medium: [
      'Frag einen Fremden nach seinem besten Reise-Tipp und teil ihn mit der Gruppe.',
      'Lerne ein Wort in der Sprache eines Mitreisenden und benutz es.',
      'Finde jemanden, der schon am Ort war, wo du als Nächstes hinwillst.',
      'Bring jemanden aus einem anderen Zimmer dazu, mit euch anzustoßen.',
      'Tausch für eine Stunde ein Kleidungsstück mit jemand aus deinem Dorm.',
      'Frag einen Fremden, ob er dir seinen Heimatort auf Google Maps zeigt.',
      'Überzeuge jemanden aus einer anderen Gruppe, euch für 10 Minuten zu joinen.',
      'Organisiere ein spontanes Mini-Quiz über Länder und Hauptstädte mit 3 Fremden.',
      'Finde jemanden der Veganer ist und lass ihn das beste vegane Restaurant vor Ort empfehlen.',
      'Bring jemanden dazu, dir beizubringen, wie man in seiner Sprache "Du bist cool" sagt.',
      'Finde jemanden der schon mehr als 30 Länder bereist hat.',
      'Überzeuge jemanden, dir seinen liebsten Reise-Hack zu verraten.',
      'Frag 3 Fremde nach dem schlechtesten Hostel das sie je hatten.',
      'Finde jemanden der gerade seinen Geburtstag auf Reisen feiert.',
      'Überzeuge eine fremde Person, dir ihre beste lokale Restaurantempfehlung zu geben.',
      'Bring jemanden dazu, mit dir ein Foto vom Hostel zu machen.',
      'Finde jemanden der seinen Trip verlängert hat und frag warum.',
      'Lerne in 5 Minuten 5 Wörter in einer fremden Sprache von einem Mitreisenden.',
      'Frag 3 Fremde: "Was war dein schlimmster Reise-Fail?"',
      'Organisiere ein spontanes Abendessen mit 2 Fremden aus dem Hostel.',
    ],
    hard: [
      'Frag einen Fremden im Hostel nach seiner verrücktesten Reise-Geschichte – auf Video.',
      'Bring jemanden aus einem anderen Land dazu, ein Wort in seiner Sprache zu lehren – auf Video.',
      'Organisier ein Mini-Spiel mit 3 Fremden aus dem Gemeinschaftsraum.',
      'Lass dir von einem Mitreisenden sein bestes Foto vom Trip zeigen und erklären.',
      'Bring 3 Personen aus verschiedenen Ländern zusammen für ein Gruppenfoto.',
      'Überzeuge 3 Fremde, dir die peinlichste Sache zu erzählen, die ihnen auf Reisen passiert ist.',
      'Finde jemanden der allein reist und überzeuge ihn, heute Abend mit euch mitzukommen.',
      'Organizer ein Hostel-Trivia mit 5 Fremden.',
      'Bring jemanden dazu, dir beizubringen wie man in seiner Sprache flirtet — auf Video.',
      'Finde jemanden, der gerade ein Problem mit seiner Reise hat, und löst es zusammen.',
      'Organisiere eine Wett-Trinkreise durch den Gemeinschaftsraum mit 3 Fremden.',
      'Bring einen Fremden dazu, dir seinen komplett geplanten Tagesablauf für morgen zu erzählen.',
      'Finde jemanden aus einer komplett anderen Weltregion und lern 3 Dinge über seine Heimat.',
      'Überzeuge 3 verschiedene Reisende, euch ein gemeinsames Selfie zu machen.',
      'Finde jemanden der mindestens ein Jahr non-stop gereist ist.',
      'Organisiere ein spontanes internationales Abendessen: jeder bringt einen lokalen Snack.',
      'Bring 5 Fremde dazu, einen gemeinsamen Toast auf das Reisen zu machen.',
      'Interviewe 3 Reisende auf Video: "Was hast du auf dieser Reise gelernt?"',
      'Überzeuge jemanden, dir für eine Stunde seine Reisetagebuch-App zu zeigen.',
      'Bringe jemanden dazu, mit der Gruppe eine spontane Stadtführung zu machen.',
    ],
    chaos: [
      'Eine fremde Person aus deinem Dorm entscheidet, wer bestraft wird.',
      'Tausch für den Rest des Abends deinen Vornamen mit jemand Fremdem.',
      'Lass dir spontan einen Spitznamen von jemand Fremdem geben – und benutz ihn.',
      'Der am weitesten gereiste Fremde im Raum wählt deine nächste Challenge.',
      'Frag 3 Fremde nacheinander: "Was ist dein peinlichster Reise-Moment?"',
      'Alle Mitspieler tauschen für 10 Minuten ihre Reise-Pläne.',
      'Die gesamte Gruppe muss sich 5 Minuten lang auf Englisch unterhalten.',
      'Wer als Letzter eine Hauptstadt nennen kann, trinkt.',
      'Lass einen Fremden entscheiden, was die Gruppe heute Abend unternimmt.',
      'Alle zeigen das peinlichste Foto aus ihrer Kamerarolle — Fremde im Hostel wählen das Schlechteste.',
      'Tausch für eine Runde dein Getränk mit dem eines Fremden.',
      'Die Gruppe muss gemeinsam in 2 Minuten ein spontanes Abenteuer für morgen planen.',
      'Überzeuge 5 Fremde, alle gleichzeitig "Prost!" auf verschiedenen Sprachen zu sagen.',
      'Wer zuerst ein Selfie mit einem Fremden macht, ist safe — alle anderen trinken.',
      'Alle Handys in die Mitte — wer als Erstes schaut, trinkt doppelt.',
      'Lass einen Fremden per Losverfahren das Dare für den nächsten Mitspieler wählen.',
      'Die Gruppe tauscht für 3 Runden die Sitzplätze nach einem Zufallsprinzip.',
      'Bring alle im Gemeinschaftsraum dazu, gleichzeitig aufzustehen.',
      'Wer als Letztes "Hostel-Alarm!" ruft, zahlt die nächste Runde.',
      'Alle nennen gleichzeitig ein Reiseziel — wer dasselbe nennt wie ein anderer, trinkt.',
    ],
  },

  // ════════════════════════════════════════════════════════
  // 🏠 HAUSPARTY
  // ════════════════════════════════════════════════════════
  houseparty: {
    easy: [
      'Finde etwas Gelbes im Raum und bring es zur Gruppe.',
      'Mach eine Foto-Pose mit der Person rechts von dir.',
      'Bring jemanden zum Lachen, ohne zu sprechen.',
      'Tanze 10 Sekunden lang ohne Musik.',
      'Finde jemanden mit dem gleichen Schuhwerk wie du.',
      'Sag dem Spieler links ein echtes Kompliment.',
      'Mach das peinlichste Selfie das du kannst und zeig es herum.',
      'Sag dreimal schnell hintereinander: "Brötchen, Brötchen, Brötchen".',
      'Halte 30 Sekunden lang Augenkontakt mit dem Spieler gegenüber.',
      'Zeig das älteste Foto auf deinem Handy.',
      'Mach für 15 Sekunden Planke.',
      'Erzähl einen schlechten Witz.',
      'Sag jedem Mitspieler seinen Tier-Typ.',
      'Mach für 20 Sekunden den Worm-Dance.',
      'Zeig deine Notizen-App — lies den letzten Eintrag vor.',
      'Nenn drei Dinge die du heute noch nicht gesagt hast.',
      'Mach die beste Zeitlupe-Bewegung beim Öffnen einer Flasche.',
      'Sag "no cap" in jedem Satz für die nächsten 2 Minuten.',
      'Finde etwas im Raum das mit dem Buchstaben "S" anfängt.',
      'Steh für die nächste Runde — kein Sitzen erlaubt.',
    ],
    medium: [
      'Singe die erste Zeile eines Songs vor der Gruppe.',
      'Tausch für eine Runde ein Kleidungsstück mit einem Mitspieler.',
      'Imitiere einen anderen Spieler, bis die Gruppe errät, wer es ist.',
      'Erzähl die peinlichste Geschichte, die dir gerade einfällt.',
      'Bring jemanden dazu, mit dir auf einen Spruch anzustoßen, den du erfindest.',
      'Zeig deinen Spotify-Wrapped oder deine zuletzt gehörte Playlist.',
      'Lies deinen letzten WhatsApp-Chat-Verlauf der Gruppe vor.',
      'Mach die beste Imitation eines berühmten Politikers.',
      'Erkläre TikTok so als würdest du mit einer 80-jährigen Person sprechen.',
      'Schreib die Namen aller Mitspieler auf — wer fehlt, trinkt.',
      'Erfinde sofort einen Cocktail-Namen für jeden Mitspieler.',
      'Erkläre in 30 Sekunden warum du der/die beste Mitspieler:in bist.',
      'Sag jedem Mitspieler was du an ihm wirklich nervt — in Liebessprache verpackt.',
      'Improvisiere eine 20-Sekunden Werbung für dich selbst.',
      'Mach die beste Imitation des Spielers links von dir — die Gruppe rät wer.',
      'Erkläre ChatGPT so als wärst du ein mittelalterlicher Bauer.',
      'Ranking: Sortiere alle Mitspieler von "schlaf­endste Person auf einer Party" bis "letzter der geht".',
      'Zeig dein peinlichstes Kamerollen-Foto von vor einem Jahr.',
      'Nenn für jeden Mitspieler einen Superhelden der zu ihm passt.',
      'Sag drei wahre Sätze und eine Lüge — die Gruppe rät welche die Lüge ist.',
    ],
    hard: [
      'Erzähl einem Mitspieler einen Witz und film die Reaktion.',
      'Lass dir von der Gruppe ein Kompliment auf Video geben.',
      'Tausch für 2 Runden deinen Sitzplatz mit einem zufällig gewählten Spieler.',
      'Mach eine Mini-Performance (Tanz, Gesang, Schauspiel) für die Gruppe.',
      'Verrate dein peinlichstes Party-Erlebnis – die Gruppe stimmt ab, ob sie\'s glaubt.',
      'Zeig das peinlichste Bild deiner gesamten Kamerarolle — kein Auswählen, erstes Scrollen entscheidet.',
      'Ruf auf Lautsprecher deine Eltern an und sag "Ich bin verliebt." Zeig die Antwort.',
      'Lies den letzten Text vor, den du verschickt hast — komplett, ohne Auslassungen.',
      'Sag allen Mitspielern offen: Wen würdest du niemals daten — und warum?',
      'Schreib einer zufälligen Person in deinen Kontakten "Ich vermisse dich" und zeig die Antwort.',
      'Teile die peinlichste Sache, die du je getan hast — kein Herumreden.',
      'Ranking live: Sortiere alle Mitspieler von "attraktivsten" bis "am wenigsten attraktiven".',
      'Zeig deine Screen-Time der letzten Woche.',
      'Hinterlasse eine Sprachnachricht auf deiner eigenen Nummer — die Gruppe wählt den Inhalt.',
      'Post ein Foto von dir mit dem Caption "glow-up incoming 🔥" — jetzt sofort.',
      'Schick deinem Boss oder Lehrer: "Können wir mal reden? Ist wichtig." Zeig die Antwort.',
      'Zeig der Gruppe deine zuletzt angesehenen YouTube-Videos.',
      'Lass die Gruppe deinen nächsten Instagram-Post gestalten — und post ihn wirklich.',
      'Ruf eine zufällige Nummer in deinen Kontakten an und sag: "Ich brauche deinen ehrlichsten Rat."',
      'Teile deinen größten noch nicht erfüllten Lebenswunsch — in einem Satz, ehrlich.',
    ],
    chaos: [
      'Die Gruppe entscheidet per Mehrheit, wer als Nächstes bestraft wird.',
      'Tausch für 2 Runden deinen Charakter-Namen mit einem Mitspieler.',
      'Der Verlierer der letzten Runde wählt deine nächste Challenge.',
      'Gib dein Handy für 1 Minute an die Person rechts von dir.',
      'Lass die Gruppe per Mehrheitsentscheid deine Strafe verdoppeln oder halbieren.',
      'Alle Handys in die Mitte — wer als Erstes schaut, trinkt doppelt.',
      'Wer als Letzter "Hausparty-Alarm!" ruft, trinkt.',
      'Die Gruppe wählt per Abstimmung wer die peinlichste Person im Raum ist — die trinkt.',
      'Alle stehen auf — wer als Letztes sitzt, trinkt.',
      'Waterfall: Du fängst an zu trinken, alle folgen. Erst wenn du aufhörst, darf die nächste Person aufhören.',
      'Most Likely: Wer würde am ehesten versehentlich die Polizei rufen? Meistgenannte Person trinkt.',
      'Speed Round: Alle nennen einen Promi in 5 Sekunden — wer wiederholt, trinkt.',
      'Verteile 5 Schlucke an wen du willst.',
      'Wähle eine Regel für die nächsten 2 Runden — jeder der sie bricht, trinkt.',
      'Die Gruppe tauscht die Sitzplätze reihum — wer zögert, trinkt.',
      'Jeder flüstert dem Spieler rechts eine Aufgabe — alle führen sie gleichzeitig aus.',
      'Du und der Spieler links trinkt zusammen für 3 Sekunden — wer früher aufhört, trinkt nochmal.',
      'Alle nennen gleichzeitig eine Farbe — wer allein eine Farbe nennt, ist safe. Alle anderen trinken.',
      'Bestimme: Wer muss bis zur nächsten Runde nichts sagen?',
      'Finger auf der Nase: Letzter der es tut, trinkt.',
    ],
  },

  // ════════════════════════════════════════════════════════
  // 🏖️ URLAUB
  // ════════════════════════════════════════════════════════
  vacation: {
    easy: [
      'Finde etwas in der Farbe des Meeres/Pools in der Nähe.',
      'Mach eine Urlaubs-Pose für ein Foto.',
      'Finde jemanden mit Sonnenbrille und frag nach einem Foto.',
      'Bau in 30 Sekunden etwas aus Sand oder was greifbar ist.',
      'Bring jemanden dazu, "Prost auf den Urlaub" zu sagen.',
      'Finde jemanden der einen Sonnenbrand hat.',
      'Zeig das beste Urlaubs-Foto das du bisher gemacht hast.',
      'Finde jemanden der ein Buch am Strand oder Pool liest.',
      'Mach das beste "ich bin im Urlaub"-Selfie.',
      'Finde jemanden der einen farbigen Drink bestellt hat.',
      'Sag drei Dinge die du heute noch erleben willst.',
      'Find jemanden der schon in diesem Land war bevor.',
      'Mach für 15 Sekunden den entspanntesten "Ich bin im Urlaub"-Move.',
      'Finde jemanden der Local-Food gegessen hat heute.',
      'Frag einen Fremden nach der besten Spot für Sunset.',
      'Mach ein Foto mit dem blausten Himmel/Wasser im Hintergrund.',
      'Finde jemanden der ohne Sonnencreme unterwegs ist.',
      'Bring jemanden dazu, dir ein Wort in der lokalen Sprache beizubringen.',
      'Finde etwas das typisch für dieses Land ist.',
      'Zeig deinen Lieblingsmoment aus dem Urlaub bisher.',
    ],
    medium: [
      'Frag jemand Fremdes am Pool/Strand nach einem Insider-Tipp für die Gegend.',
      'Mach ein Urlaubsfoto mit einem kompletten Fremden.',
      'Bestell etwas auf Landessprache (oder versuch\'s zumindest).',
      'Finde jemanden, der schon mal an deinem Heimatort war.',
      'Tausch für eine Stunde deine Sonnenbrille mit jemandem aus der Gruppe.',
      'Frag 3 Fremde nach dem besten lokalen Gericht das du probieren musst.',
      'Überzeuge jemanden, mit euch schwimmen zu gehen.',
      'Finde jemanden der einen ausgefallenen Hut trägt und frag woher er ist.',
      'Mach ein "typisches Tourist"-Foto und eines das beweist du kein Tourist bist.',
      'Bring jemanden dazu, dir die beste lokale Cocktail-Empfehlung zu geben.',
      'Frag 3 Fremde: "Was ist das Unvergesslichste das du hier erlebt hast?"',
      'Organisiere ein spontanes Strandspiel mit 2 Fremden.',
      'Finde jemanden der die lokale Sprache fließend spricht und lern 5 Wörter.',
      'Bring jemanden dazu, mit euch das Sonnenuntergang anzuschauen.',
      'Finde jemanden der solo reist und überzeuge ihn, sich für 10 Minuten dazuzusetzen.',
      'Frag einen Einheimischen nach dem geheimsten Spot in der Nähe.',
      'Mach ein Zeitraffer-Selfie vom Pool/Strand.',
      'Organisiere ein spontanes Sandburg-Battle mit der Gruppe.',
      'Überzeuge 3 Fremde, mit euch einen Toast auf den Urlaub zu machen.',
      'Finde jemanden der das gleiche Hotel/Airbnb-Ziel hat wie ihr.',
    ],
    hard: [
      'Frag einen Local nach seinem besten Geheimtipp – auf Video.',
      'Bring einen Fremden dazu, ein Wort in seiner Sprache zu lehren – auf Video.',
      'Organisier ein Spontan-Wettrennen (Pool, Strand, Flur) mit 2 Mitspielern.',
      'Lass dir von einem Fremden eine Souvenir-Empfehlung geben und erklären, warum.',
      'Mach mit einer fremden Reisegruppe ein gemeinsames Gruppenfoto.',
      'Überzeuge einen Fremden, dir die lokale Geschichte eines Gebäudes zu erklären.',
      'Bring eine fremde Gruppe dazu, ein spontanes Volleyball/Beachball-Spiel zu starten.',
      'Finde jemanden der etwas über diesen Ort weiß das du noch nicht wusstest.',
      'Interviewe 3 Locals: "Was sollen Touristen auf keinen Fall tun?"',
      'Bring jemanden dazu, mit dir 10 Minuten lang nichts zu sagen — nur den Sonnenuntergang geniessen.',
      'Überzeuge 5 Fremde, für 30 Sekunden gemeinsam zu posieren.',
      'Finde jemanden der hier schon 3+ Mal war und lass dir die Top 3 Tipps geben.',
      'Organisiere ein spontanes Quiz über das Land mit 3 Fremden.',
      'Bring einen Fremden dazu, dir die besten lokalen Street-Food-Spots zu zeigen.',
      'Überzeuge 3 Fremde, mit euch ein gemeinsames "Urlaubsselfie" zu machen.',
      'Finde jemanden der hier arbeitet und frag nach dem besten Abend-Tipp.',
      'Bring eine Gruppe dazu, gemeinsam ins Wasser zu springen — auf ein Zeichen.',
      'Organisiere ein spontanes Kartenspiel mit Fremden.',
      'Lass 3 verschiedene Locals abstimmen: Was ist das Beste an diesem Ort?',
      'Bring jemanden dazu, mit euch einen lokalen Snack auszuprobieren.',
    ],
    chaos: [
      'Eine fremde Person am Pool/Strand entscheidet, wer bestraft wird.',
      'Tausch für 2 Runden deinen Namen mit der Person neben dir.',
      'Der Verlierer der letzten Runde wählt dein nächstes Urlaubsfoto-Motiv.',
      'Lass die Gruppe entscheiden, was du als Nächstes bestellst.',
      'Frag 3 Fremde nacheinander nach ihrem besten Urlaubsmoment – auf Video.',
      'Alle müssen für die nächsten 5 Minuten auf Englisch sprechen — wer Fehler macht, trinkt.',
      'Wer als Letzter "Urlaubs-Alarm!" ruft, trinkt.',
      'Die Gruppe tauscht die Sitzplätze nach einem Zufallsprinzip — wer meckert, trinkt.',
      'Alle stehen auf — wer als Letztes sitzt, trinkt.',
      'Most Likely: Wer vergisst am ehesten den Sonnenschutz? Meistgenannte Person trinkt.',
      'Verteile 5 Schlucke an wen du willst.',
      'Wähle eine Urlaubs-Regel für die nächsten 2 Runden — jeder der sie bricht, trinkt.',
      'Speed Round: Alle nennen ein Urlaubsziel in 5 Sekunden — wer wiederholt, trinkt.',
      'Wer als Letzter "Sonnencreme!" ruft, trinkt.',
      'Alle Handys in die Mitte — wer als Erstes schaut, trinkt doppelt.',
      'Finger auf die Nase: Letzter der es tut, trinkt.',
      'Die Gruppe wählt: Du musst entweder ins Wasser springen oder trinkst doppelt.',
      'Alle nennen gleichzeitig ein Tier das man hier antreffen könnte — wer dasselbe nennt wie ein anderer, trinkt.',
      'Wer zuerst "Feierabend!" ruft, bestimmt das nächste Dare.',
      'Waterfall auf Urlaubs-Art: Alle trinken bis die erste Person aufhört — dann darf die nächste aufhören.',
    ],
  },
}

// ============================================================
// 🇬🇧 ENGLISH CHALLENGE POOL
// ============================================================

export const CHALLENGES_BY_LOCATION_EN = {

  // 🍸 BAR
  bar: {
    easy: [
      'Order a drink using only hand gestures.',
      'Find someone with the same drink as you.',
      'Toast with three different strangers.',
      'Ask the bartender to recommend their favorite drink.',
      'Take a selfie with the bartender.',
      'Find someone wearing sunglasses inside.',
      'Compliment the bartender on something specific.',
      'Order your next drink in a different accent.',
      'Find someone who\'s celebrating something tonight.',
      'Do the Matrix slow-motion move for 20 seconds.',
      'Show the player to your left your contact list — pick a random name and read it aloud.',
      'Swap your barstool with someone else for one round.',
      'Shout "Cheers!" and see who raises their glass.',
      'Use the word "legendary" three times in the next 2 minutes.',
      'Let the bartender guess what your favorite drink is.',
      'Order something you\'ve never had before.',
      'Find someone wearing a watch and ask them the time dramatically.',
      'Show your phone wallpaper to the bartender.',
      'Find someone drinking the same color drink as you.',
      'Tell a stranger at the bar they look like a celebrity.',
    ],
    medium: [
      'Ask a stranger for a drink recommendation without telling them what you like.',
      'Make the bartender laugh without saying a word.',
      'Find someone with a cocktail and describe how you think it tastes.',
      'Introduce yourself to a stranger group as someone famous from your hometown.',
      'Ask 3 different people at the bar what their favorite bar is.',
      'Describe your drink as if you\'re a wine sommelier.',
      'Find someone sitting alone and give them a genuine compliment.',
      'Make up a handshake with a complete stranger.',
      'Tell the bartender a joke and see if they laugh.',
      'Find someone with a cocktail umbrella in their drink.',
      'Imitate the bartender for 30 seconds.',
      'Ask 3 strangers what their favorite movie is.',
      'Explain to a stranger what your drink says about your personality.',
      'Introduce yourself to a group with a made-up job title.',
      'Let the group decide what you order next.',
      'Ask the bartender for the strangest cocktail they know.',
      'Find someone and convince them to try a sip of your drink.',
      'Tell the player to your right how to correctly drink their drink.',
      'Order a drink and give it a dramatic name you invented.',
      'Challenge someone at the bar to 20 questions — loser buys a round.',
    ],
    hard: [
      'Get a stranger to say "Cheers!" with you on video.',
      'Ask the bartender for the most embarrassing order they\'ve had tonight.',
      'Get a stranger to give you a compliment on camera.',
      'Swap your spot with a complete stranger at the bar for one round.',
      'Tell a joke to the bar crowd and film the reaction.',
      'Find a stranger and convince them to join your group.',
      'Order in a language you don\'t speak — ask a stranger how first.',
      'Do a 30-second stand-up performance at the bar.',
      'Get 5 strangers to all toast at the same time.',
      'Ask a stranger "What\'s your biggest secret?" and film the reaction.',
      'Convince the bartender to make you a free drink using only charm, no money.',
      'Find someone with an expensive drink and ask for a sip.',
      'Introduce yourself to 5 strangers — each time with a different made-up name.',
      'Swap phones with the player to your left for 5 minutes — you can\'t look at anything.',
      'Get a stranger to share their most embarrassing bar story.',
      'Sit alone at the bar for 2 minutes and ignore everyone.',
      'Let a stranger decide what you drink next.',
      'Take a selfie with 3 different strangers.',
      'Ask 5 strangers "Who are you really?" and film the answers.',
      'Take over a stranger\'s barstool — with their permission — for 1 minute.',
    ],
    chaos: [
      'Let the bartender choose your next drink — eyes closed.',
      'A stranger at the bar decides who gets the next punishment.',
      'Swap your name for 2 rounds with the person next to you at the bar.',
      'The group decides: your next drink gets mixed with something random.',
      'Ask 3 strangers in a row about their most embarrassing bar moment.',
      'Stand on your chair for 3 minutes — whoever comments drinks.',
      'Take over as bartender for 1 minute and take drink orders.',
      'All players give you a task — you do the hardest one.',
      'Order a drink that doesn\'t exist and convince the bartender to invent it.',
      'Whoever makes a stranger laugh last drinks double.',
      'Secretly switch two players\' drinks without them noticing.',
      'Get the whole group to yell "Cheers!" simultaneously.',
      'Shout "Who\'s single here?" — the first to raise their hand gets a compliment from you.',
      'Let a random stranger choose your next dare.',
      'Everyone stands — last to sit pays for the next round.',
      'Swap drinks with the player opposite you for 3 rounds.',
      'Convince a stranger group to do a rehearsed group toast with you.',
      'The group votes: either you drink double, or you shout your full name loudly.',
      'Let 3 strangers vote on who\'s the coolest in your group.',
      'Whoever puts their glass down first drinks another.',
    ],
  },

  // 🎪 FESTIVAL
  festival: {
    easy: [
      'Find someone with glitter on their face.',
      'Dance for 15 seconds to whatever music is playing around you.',
      'Find an outfit in your favorite color in the crowd.',
      'Do a group pose with 3 strangers.',
      'Get someone to sing along with you.',
      'Find someone wearing a hat.',
      'Wave at a stranger — wait for the reaction.',
      'Find someone with a festival wristband.',
      'Take a photo with the first stranger you meet.',
      'Tell a stranger you love their style.',
      'Dance for 10 seconds with your eyes closed.',
      'Find someone who has the same favorite artist as you.',
      'Get a stranger to teach you how to say "cool" in their language.',
      'Find someone wearing an animal costume or accessory.',
      'Do your best air guitar for 15 seconds.',
      'Sing the first line of a current chart hit out loud.',
      'Find someone with a flag painted on their cheek.',
      'Stand completely still for 30 seconds in the middle of the crowd.',
      'Find someone wearing festival merchandise.',
      'Show your best "completely unimpressed festival-goer" face.',
    ],
    medium: [
      'Learn the dance move of the person next to you and copy it.',
      'Find someone with face paint and ask who painted it.',
      'Start a wave with at least 5 people around you.',
      'Swap bracelets with a stranger for an hour.',
      'Get a stranger group to cheer with you.',
      'Find someone who just arrived and explain the "most important festival rules."',
      'Make a boomerang video with 5 strangers.',
      'Find someone who loves the same artist as you.',
      'Get a stranger to dance with you for at least 20 seconds.',
      'Explain the top 3 festival hacks to a stranger.',
      'Find someone who already looks exhausted before the main act.',
      'Get a group of strangers to take a photo together.',
      'Freestyle rap about the festival for 15 seconds — in front of strangers.',
      'Find someone who looks completely different from you and take a duo selfie.',
      'Get 5 strangers to raise their hands at the same time.',
      'Do your best "I\'m a veteran festival-goer" impression.',
      'Swap sunglasses with a stranger for 10 minutes.',
      'Find someone using a selfie stick and ask for a photo.',
      'Tell the player to your left what your outfit says about you.',
      'Get a group of strangers to do a countdown with you.',
    ],
    hard: [
      'Get a completely random group to take a photo with you.',
      'Learn the names of 3 strangers in 2 minutes and introduce them to the group.',
      'Start a dance circle and get 5 people to join.',
      'Ask a stranger about their best festival memory — on video.',
      'Get the crowd around you to chant your name.',
      'Conduct a mini-interview with 3 strangers: "Why are you here?"',
      'Get someone to spontaneously give you a nickname.',
      'Organize a spontaneous choir with 5 strangers for 10 seconds.',
      'Convince a stranger group to join you for 5 minutes.',
      'Find the person with the coolest outfit and convince them to do a brief catwalk.',
      'Get a row of strangers to cheer simultaneously on your signal.',
      'Start a trend: invent a move and get 5 strangers to copy it.',
      'Film interviews — ask 5 strangers "What\'s your festival life motto?"',
      'Get the person next to you to carry you on their shoulders for 30 seconds.',
      'Convince a stranger to sing their favorite song for you.',
      'Find the loudest person nearby and out-shout them.',
      'Get 10 strangers to clap at the same time.',
      'Convince a group to cheer you on: everyone shouts "You\'ve got this!"',
      'Tell a stranger on video why they\'re the coolest festival-goer there.',
      'Get someone to lend you their festival flag or accessory.',
    ],
    chaos: [
      'A stranger from the crowd decides who gets the punishment.',
      'Swap a piece of clothing with a stranger for 2 rounds.',
      'Get the group around you to teach you a mini-choreography.',
      'The loudest stranger near you picks your next challenge.',
      'Collect high-fives from 10 strangers in 60 seconds.',
      'All players vote — you do the move the majority chooses.',
      'Swap your spot with the player opposite for 10 minutes.',
      'Find someone and get them to give the group their best scream.',
      'The group picks a stranger — you must make them a friend in 60 seconds.',
      'Let the crowd vote: are you a "main stage type" or a "hidden gem fan"?',
      'Get all players dancing for 30 seconds — whoever stops drinks.',
      'The next stranger who walks past decides who loses this round.',
      'All phones in the middle — first to check theirs drinks double.',
      'Let 3 strangers vote on who\'s the funniest in the group.',
      'Swap everything in your pockets with the player to your left for one round.',
      'Get the whole group to stay completely silent for 10 seconds.',
      'Whoever stops dancing first when the music stops picks the next dare.',
      'All players say a word simultaneously — build a sentence from them and say it to strangers.',
      'Let a stranger decide which group member gets the next penalty.',
      'Take on the character name of the player to your right for 2 rounds.',
    ],
  },

  // 🎒 HOSTEL
  hostel: {
    easy: [
      'Ask someone in the common room where they\'re from.',
      'Find someone from a different country than you.',
      'Share a travel tip with a stranger in the hostel.',
      'Find someone with the same type of backpack as you.',
      'Introduce yourself to three people in the common room.',
      'Ask a stranger what their favorite travel destination is.',
      'Find someone who has visited more than 10 countries.',
      'Find someone who\'s on their way home.',
      'Ask someone: "What\'s the craziest thing that happened to you while traveling?"',
      'Find someone who\'s reading a book or has an e-reader.',
      'Show a stranger your favorite photo from this trip.',
      'Ask someone what their next destination is.',
      'Find someone who speaks more than 3 languages.',
      'Learn "hello" in the language of the person next to you.',
      'Ask 3 strangers for a local restaurant recommendation.',
      'Find someone who just arrived.',
      'Show a stranger your travel plan and ask for tips.',
      'Find someone with a souvenir and ask to see it.',
      'Ask someone: "What do you miss most from home right now?"',
      'Find someone who\'s traveling solo.',
    ],
    medium: [
      'Ask a stranger for their best travel hack and share it with the group.',
      'Learn a word in a fellow traveler\'s language and use it in a sentence.',
      'Find someone who\'s already been to where you\'re going next.',
      'Get someone from another room to toast with you.',
      'Swap a piece of clothing with someone from your dorm for one hour.',
      'Ask a stranger to show you their hometown on Google Maps.',
      'Convince someone from another group to join yours for 10 minutes.',
      'Organize a mini-quiz about countries and capitals with 3 strangers.',
      'Find a vegan and get them to recommend the best vegan restaurant nearby.',
      'Get someone to teach you how to say "you\'re cool" in their language.',
      'Find someone who\'s visited more than 30 countries.',
      'Convince someone to share their best-kept travel secret.',
      'Ask 3 strangers about the worst hostel they\'ve ever stayed in.',
      'Find someone who\'s celebrating their birthday while traveling.',
      'Convince a stranger to give you their best local restaurant tip.',
      'Get someone to take a photo of the hostel with you.',
      'Find someone who extended their trip and ask why.',
      'Learn 5 words in a foreign language from a fellow traveler in 5 minutes.',
      'Ask 3 strangers: "What was your biggest travel fail?"',
      'Organize a spontaneous dinner with 2 strangers from the hostel.',
    ],
    hard: [
      'Ask a stranger in the hostel about their craziest travel story — on video.',
      'Get someone from another country to teach you a word in their language — on video.',
      'Organize a mini-game with 3 strangers from the common room.',
      'Get a fellow traveler to show you their best photo from the trip and explain it.',
      'Get 3 people from different countries together for a group photo.',
      'Convince 3 strangers to share the most embarrassing thing that happened while traveling.',
      'Find someone traveling solo and convince them to join you tonight.',
      'Organize a hostel trivia game with 5 strangers.',
      'Get someone to teach you how to flirt in their language — on video.',
      'Find someone having a travel problem right now and solve it together.',
      'Organize a drinking relay through the common room with 3 strangers.',
      'Get a stranger to tell you their complete itinerary for tomorrow.',
      'Find someone from a completely different region of the world and learn 3 things about their home.',
      'Convince 3 different travelers to take a group selfie with you.',
      'Find someone who\'s been traveling non-stop for at least a year.',
      'Organize a spontaneous international dinner: everyone brings a local snack.',
      'Get 5 strangers to make a joint toast to traveling.',
      'Interview 3 travelers on video: "What have you learned on this trip?"',
      'Convince someone to show you their travel journal app for one hour.',
      'Get someone to give the group a spontaneous local tour.',
    ],
    chaos: [
      'A stranger from your dorm decides who gets the punishment.',
      'Swap your first name with a stranger for the rest of the evening.',
      'Let a stranger spontaneously give you a nickname — and use it.',
      'The most-traveled stranger in the room picks your next challenge.',
      'Ask 3 strangers in a row about their most embarrassing travel moment.',
      'All players swap travel plans for 10 minutes.',
      'The whole group must speak only English for 5 minutes — whoever slips up drinks.',
      'Whoever is last to name a capital city drinks.',
      'Let a stranger decide what the group does tonight.',
      'Everyone shows the most embarrassing photo from their camera roll — hostel strangers pick the worst.',
      'Swap your drink with a stranger for one round.',
      'The group must plan a spontaneous adventure for tomorrow in 2 minutes.',
      'Convince 5 strangers to all say "Cheers!" in different languages simultaneously.',
      'Whoever takes a selfie with a stranger first is safe — everyone else drinks.',
      'All phones in the middle — first to check theirs drinks double.',
      'Let a stranger randomly pick the dare for the next player.',
      'The group swaps seats for 3 rounds based on a random system.',
      'Get everyone in the common room to stand up at the same time.',
      'Whoever shouts "Hostel alarm!" last drinks the next round.',
      'Everyone names a destination simultaneously — whoever says the same as another player drinks.',
    ],
  },

  // 🏠 HOUSE PARTY
  houseparty: {
    easy: [
      'Find something yellow in the room and bring it to the group.',
      'Strike a photo pose with the player to your right.',
      'Make someone laugh without speaking.',
      'Dance for 10 seconds without music.',
      'Find someone with the same shoes as you.',
      'Give the player to your left a genuine compliment.',
      'Take the most embarrassing selfie you can and show it around.',
      'Say "party time" three times fast and really mean it.',
      'Hold eye contact with the player opposite you for 30 seconds.',
      'Show the oldest photo on your phone.',
      'Hold a plank for 15 seconds.',
      'Tell a terrible joke.',
      'Assign each player an animal type.',
      'Do the worm for 20 seconds.',
      'Show your notes app — read the last entry aloud.',
      'Name 3 things you haven\'t said yet today.',
      'Do the best slow-motion move while opening a bottle.',
      'Say "no cap" in every sentence for the next 2 minutes.',
      'Find something in the room that starts with the letter "S."',
      'Stand for the next round — no sitting allowed.',
    ],
    medium: [
      'Sing the first line of a song in front of the group.',
      'Swap a piece of clothing with a player for one round.',
      'Imitate another player until the group guesses who it is.',
      'Tell the most embarrassing story that comes to mind right now.',
      'Get someone to toast with you using a catchphrase you make up on the spot.',
      'Show your Spotify Wrapped or your most recently played playlist.',
      'Read your last chat conversation aloud to the group.',
      'Do the best impression of a famous politician.',
      'Explain TikTok as if you\'re talking to an 80-year-old.',
      'Write down the names of all the players — whoever is missing drinks.',
      'Instantly invent a cocktail name for each player.',
      'Explain in 30 seconds why you\'re the best player here.',
      'Tell each player what actually annoys you about them — wrapped in a compliment.',
      'Improvise a 20-second advertisement for yourself.',
      'Imitate the player to your left — the group guesses who.',
      'Explain AI as if you\'re a medieval peasant.',
      'Ranking: sort all players from "most likely to fall asleep first" to "last to leave."',
      'Show the most embarrassing photo from your camera roll from exactly one year ago.',
      'Name a superhero that matches each player.',
      'Say 3 true sentences and one lie — the group guesses which is the lie.',
    ],
    hard: [
      'Tell a player a joke and film the reaction.',
      'Get the group to give you a compliment on camera.',
      'Swap your seat with a randomly chosen player for 2 rounds.',
      'Do a mini-performance (dance, sing, act) for the group.',
      'Share your most embarrassing party story — the group votes on whether they believe it.',
      'Show the most embarrassing photo in your entire camera roll — no choosing, just scroll and stop.',
      'Call your parents on speaker and say "I think I\'m in love." Show the reply.',
      'Read the last text you sent aloud — completely, no skipping.',
      'Tell everyone openly: who would you never date — and why?',
      'Text a random person in your contacts "I miss you" and show the reply.',
      'Share the most embarrassing thing you\'ve ever done — no beating around the bush.',
      'Live ranking: sort all players from "most attractive" to "least attractive."',
      'Show your screen time from the past week.',
      'Leave a voice message on your own number — the group chooses the content.',
      'Post a photo of yourself with the caption "glow-up incoming 🔥" — right now.',
      'Text your boss or teacher: "Can we talk? It\'s important." Show the reply.',
      'Show the group your most recently watched YouTube videos.',
      'Let the group design your next Instagram post — and actually post it.',
      'Call a random contact and say: "I need your most honest advice."',
      'Share your biggest unfulfilled life wish — in one sentence, honestly.',
    ],
    chaos: [
      'The group votes on who gets the next punishment.',
      'Swap your character name with a player for 2 rounds.',
      'The loser of the last round picks your next challenge.',
      'Hand your phone to the player on your right for 1 minute.',
      'The group votes to double or halve your penalty.',
      'All phones in the middle — first to check theirs drinks double.',
      'Whoever shouts "party alarm!" last drinks.',
      'The group votes on who the most embarrassing person in the room is — they drink.',
      'Everyone stands — last to sit drinks.',
      'Waterfall: you start drinking, everyone follows. Only when you stop can the next person stop.',
      'Most Likely: who would most likely accidentally call the police? Most-voted person drinks.',
      'Speed Round: everyone names a celebrity in 5 seconds — whoever repeats one drinks.',
      'Hand out 5 sips to whoever you want.',
      'Choose a rule for the next 2 rounds — whoever breaks it drinks.',
      'The group rotates seats — whoever hesitates drinks.',
      'Everyone whispers a task to the player on their right — all perform simultaneously.',
      'You and the player to your left drink for 3 seconds — whoever stops first drinks again.',
      'Everyone names a color simultaneously — whoever\'s alone with their color is safe. Everyone else drinks.',
      'Decide: who must stay silent until the next round?',
      'Nose tap: last to do it drinks.',
    ],
  },

  // 🏖️ VACATION
  vacation: {
    easy: [
      'Find something the color of the sea or pool nearby.',
      'Strike a classic vacation pose for a photo.',
      'Find someone wearing sunglasses and ask for a photo together.',
      'Build something from sand or whatever\'s around you in 30 seconds.',
      'Get someone to say "Cheers to vacation!"',
      'Find someone with a sunburn.',
      'Show the best vacation photo you\'ve taken so far.',
      'Find someone reading a book at the beach or pool.',
      'Take the best "I\'m on vacation" selfie.',
      'Find someone who ordered a colorful drink.',
      'Name 3 things you still want to experience today.',
      'Find someone who has visited this country before.',
      'Do the most relaxed "I\'m on vacation" move for 15 seconds.',
      'Find someone who ate local food today.',
      'Ask a stranger where the best spot is to watch the sunset.',
      'Take a photo with the bluest sky or water in the background.',
      'Find someone out in the sun without sunscreen.',
      'Get someone to teach you a word in the local language.',
      'Find something typical for this country.',
      'Show your favorite moment from this vacation so far.',
    ],
    medium: [
      'Ask a stranger at the pool or beach for an insider tip for the area.',
      'Take a vacation photo with a complete stranger.',
      'Order something in the local language — or at least try.',
      'Find someone who\'s been to your hometown.',
      'Swap sunglasses with someone from the group for one hour.',
      'Ask 3 strangers for the best local dish you have to try.',
      'Convince someone to go swimming with you.',
      'Find someone with an unusual hat and ask where they got it.',
      'Take one "classic tourist" photo and one that proves you\'re not a tourist.',
      'Get someone to give you the best local cocktail recommendation.',
      'Ask 3 strangers: "What\'s the most unforgettable thing you\'ve experienced here?"',
      'Organize a spontaneous beach game with 2 strangers.',
      'Find someone who speaks the local language fluently and learn 5 words from them.',
      'Get someone to watch the sunset with you.',
      'Find a solo traveler and convince them to sit with you for 10 minutes.',
      'Ask a local for the most hidden gem spot nearby.',
      'Take a time-lapse selfie at the pool or beach.',
      'Organize a spontaneous sandcastle battle with the group.',
      'Convince 3 strangers to toast to vacation with you.',
      'Find someone staying at the same hotel or Airbnb as you.',
    ],
    hard: [
      'Ask a local for their best insider tip — on video.',
      'Get a stranger to teach you a word in their language — on video.',
      'Organize a spontaneous race (pool, beach, hallway) with 2 players.',
      'Get a stranger to give you a souvenir recommendation and explain why.',
      'Take a group photo with a complete stranger travel group.',
      'Convince a stranger to explain the local history of a building.',
      'Get a stranger group to start a spontaneous volleyball or beach ball game.',
      'Find someone who knows something about this place you didn\'t know.',
      'Interview 3 locals: "What should tourists absolutely not do here?"',
      'Get someone to spend 10 minutes silently enjoying the sunset with you.',
      'Convince 5 strangers to pose together for 30 seconds.',
      'Find someone who\'s been here 3+ times and get their top 3 tips.',
      'Organize a spontaneous quiz about the country with 3 strangers.',
      'Get a stranger to show you the best local street food spots.',
      'Convince 3 strangers to take a joint "vacation selfie" with you.',
      'Find someone who works here and ask for the best evening tip.',
      'Get a group to jump into the water simultaneously on your signal.',
      'Organize a spontaneous card game with strangers.',
      'Let 3 different locals vote: what\'s the best thing about this place?',
      'Get someone to try a local snack with you.',
    ],
    chaos: [
      'A stranger at the pool or beach decides who gets the punishment.',
      'Swap your name with the person next to you for 2 rounds.',
      'The loser of the last round picks your next vacation photo subject.',
      'Let the group decide what you order next.',
      'Ask 3 strangers in a row for their best vacation moment — on video.',
      'Everyone must speak only English for the next 5 minutes — whoever makes an error drinks.',
      'Whoever shouts "vacation alarm!" last drinks.',
      'The group rotates seats — whoever complains drinks.',
      'Everyone stands — last to sit drinks.',
      'Most Likely: who is most likely to forget their sunscreen? Most-voted person drinks.',
      'Hand out 5 sips to whoever you want.',
      'Choose a vacation rule for the next 2 rounds — whoever breaks it drinks.',
      'Speed Round: everyone names a vacation destination in 5 seconds — whoever repeats one drinks.',
      'Whoever shouts "Sunscreen!" last drinks.',
      'All phones in the middle — first to check theirs drinks double.',
      'Nose tap: last to do it drinks.',
      'The group votes: you either jump in the water or drink double.',
      'Everyone names an animal you might find here simultaneously — whoever says the same as another player drinks.',
      'Whoever shouts "Happy hour!" first picks the next dare.',
      'Vacation waterfall: everyone drinks until the first person stops — then the next can stop.',
    ],
  },
}

/**
 * Wählt eine zufällige Challenge passend zu Location-Modus und
 * Schwierigkeit. Fällt auf den Hausparty-Pool zurück, falls ein
 * unbekannter Modus übergeben wird.
 * @param {'de'|'en'} language - Sprache der Challenges
 */
export function pickRandomChallenge(difficulty, locationMode = 'houseparty', language = 'de') {
  const pool = language === 'en' ? CHALLENGES_BY_LOCATION_EN : CHALLENGES_BY_LOCATION
  const locationPool = pool[locationMode] || pool.houseparty
  const diffPool = locationPool[difficulty] || locationPool.medium
  return diffPool[Math.floor(Math.random() * diffPool.length)]
}

export function pickRandomPlayer(players, excludeIds = []) {
  const eligible = players.filter((p) => !excludeIds.includes(p.id))
  const pool = eligible.length > 0 ? eligible : players
  return pool[Math.floor(Math.random() * pool.length)]
}

// Strafen-Skalierung nach Getränk
export const PUNISHMENT_BY_DRINK = {
  beer: { mild: '1 Schluck', medium: '2 Schlucke', heavy: '4 Schlucke' },
  wine: { mild: '1 Schluck', medium: '2 Schlucke', heavy: '3 Schlucke' },
  cocktail: { mild: '1 Schluck', medium: '1 Schluck', heavy: '2 Schlucke' },
  shot: { mild: '⅛ Shot', medium: '¼ Shot', heavy: '½ Shot' },
  soft: { mild: '1 Schluck', medium: '2 Schlucke', heavy: '3 Schlucke' },
  water: { mild: '1 Schluck', medium: '2 Schlucke', heavy: '3 Schlucke' },
}

export const DRINK_OPTIONS = [
  { id: 'beer', label: 'Bier', icon: '🍺' },
  { id: 'wine', label: 'Wein', icon: '🍷' },
  { id: 'cocktail', label: 'Cocktail', icon: '🍹' },
  { id: 'shot', label: 'Shot', icon: '🥃' },
  { id: 'soft', label: 'Softdrink', icon: '🥤' },
  { id: 'water', label: 'Wasser', icon: '💧' },
]

export const CASUAL_PUNISHMENTS = {
  mild: '−5 Punkte',
  medium: '−10 Punkte, Challenge-Streak verloren',
  heavy: '−20 Punkte, Challenge-Streak verloren',
}

export function getPunishmentLabel({ gameMode, drink, punishmentLevel }) {
  if (gameMode === 'casual') {
    return CASUAL_PUNISHMENTS[punishmentLevel] || CASUAL_PUNISHMENTS.medium
  }
  const drinkTable = PUNISHMENT_BY_DRINK[drink] || PUNISHMENT_BY_DRINK.soft
  return drinkTable[punishmentLevel] || drinkTable.medium
}

// ── Proof-Type Detection ─────────────────────────────────────────────────────
// Ermittelt anhand von Keywords im Challenge-Text, welche Art von Beweis
// benötigt wird. Spart massiv Firebase-Storage im Vergleich zu immer Video.
//
//  'photo'  → ~300 KB  (Standard — alles was man zeigen kann)
//  'audio'  → ~600 KB  (Sprach-/Wort-/Sing-Challenges)
//  'video'  → ~20 MB   (Nur wenn Bewegungsablauf wichtig ist)
//  'none'   → 0 KB     (Vertrauens-Challenge, direkt zur Abstimmung)

// ── German keywords ───────────────────────────────────────────────────────────
const AUDIO_KEYWORDS_DE = [
  'sag ', 'sag auf', 'sprich', 'übersetze', 'sing ', 'singe ', 'flüster',
  'nenn ', 'erkläre', 'erzähl', 'beschreib', 'buchstabier', 'rückwärts',
  'japanisch', 'englisch', 'französisch', 'spanisch', 'chinesisch',
  'russisch', 'arabisch', 'italienisch', 'portugiesisch', 'griechisch',
  'akzent', 'stimme nach', 'stimm nach', 'rap ', 'rappe', 'beatbox',
  'zähle auf', 'zähl auf', 'liste auf', 'auf englisch', 'auf französisch',
  'auf spanisch', 'auf japanisch',
]
const VIDEO_KEYWORDS_DE = [
  'tanz', 'spring ', 'imitier', 'bewege dich', 'beweg dich', 'lauf ',
  'zeig wie', 'perform', 'breakdanc', 'moonwalk', 'cartwheel',
  'purzelbaum', 'vorwärtsrolle', 'rückwärtsrolle', 'liegestütz',
  'kniebeuge', 'hampelmann',
]
const NONE_KEYWORDS_DE = [
  'denk dir', 'stell dir vor', 'entscheide', 'wähle', 'überlege',
  'erinner dich', 'geheimnis', 'nächste runde',
]

// ── English keywords ──────────────────────────────────────────────────────────
const AUDIO_KEYWORDS_EN = [
  'say ', 'sing ', 'recite ', 'translate', 'whisper', 'describe aloud', 'spell ',
  'name ', 'explain ', 'tell ', 'rap ', 'beatbox', 'in french', 'in spanish',
  'in japanese', 'in german', 'in italian', 'in russian', 'in chinese',
  'in arabic', 'in portuguese', 'in greek', 'with an accent', 'imitate the sound',
  'read aloud', 'speak ', 'shout ',
]
const VIDEO_KEYWORDS_EN = [
  'dance ', 'jump ', 'imitate', 'move ', 'run ', 'show how', 'perform',
  'breakdanc', 'moonwalk', 'cartwheel', 'forward roll', 'backflip',
  'push-up', 'squat', 'jumping jack', 'worm ', 'plank',
]
const NONE_KEYWORDS_EN = [
  'think of', 'imagine', 'decide', 'choose ', 'consider', 'remember',
  'secret', 'next round',
]

export function getProofType(challengeText) {
  if (!challengeText) return 'photo'
  const lower = challengeText.toLowerCase()

  // Detect language by common German characters
  const isGerman = /[äöüß]/.test(lower) || lower.includes(' ich ') || lower.includes(' du ')
  const noneKw  = isGerman ? NONE_KEYWORDS_DE  : NONE_KEYWORDS_EN
  const videoKw = isGerman ? VIDEO_KEYWORDS_DE  : VIDEO_KEYWORDS_EN
  const audioKw = isGerman ? AUDIO_KEYWORDS_DE  : AUDIO_KEYWORDS_EN

  if (noneKw.some((k)  => lower.includes(k))) return 'none'
  if (videoKw.some((k) => lower.includes(k))) return 'video'
  if (audioKw.some((k) => lower.includes(k))) return 'audio'
  return 'photo'
}
